trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: Ensure .NET 6 Installed
    inputs:
      packageType: 'sdk'
      version: '6.x'  

  - task: PowerShell@2
    displayName: Verify PR
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      filePath: 'build.ps1'
      arguments: '-Target Verify-PR'
      pwsh: true
    env:      
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)  
  
  - task: PublishCodeCoverageResults@1
    displayName: Publish Code Coverage
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '**/TestResults/*/coverage.cobertura.xml'  

  - task: PowerShell@2
    displayName: Push Client Package to Nuget
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      filePath: 'build.ps1'
      arguments: '-Target PushToNuget'
      pwsh: true
    env:      
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)  